function clus = hc_correct_label_b(clus)
% hc_correct_label_b: correct order of labels to reflect order in tree
%
% Usage:
%   clus = hc_correct_label_b(clus)
%
% Args:
%   clus: cluster structure with lorder and 
%       label fields as generated by hierarchicalClus
%
% Notes
% see also hierarchicalClus.m

order_i = unique(clus.label, 'sorted')';
order_o = clus.lorder;

clus.label = changem(clus.label, order_i, order_o);
% B = CHANGEM(A, NEWVAL, OLDVAL)

clus.lorder = sort(clus.lorder)';

end
