function clus = hc_correct_label_a(clus)
% hc_correct_label_a: correct order of labels to reflect order in tree
%
% Usage:
%   clus = hc_correct_label_a(clus)
%
% Args:
%   clus: cluster structure with lorder and 
%       label fields as generated by hierarchicalClus
%
% Notes
% see also hierarchicalClus.m

% make temp copy
temp = clus;

% order labels to reflect order in tree
temp.label = temp.label(temp.lorder);

% get the order of labels and sorted renumbering
order_i = unique(temp.label, 'stable')';
order_o = sort(order_i);

% apply new sorted renumbering of labels
clus.label = changem(clus.label, order_o, order_i);
clus.lorder = clus.lorder';

end
