function fictrac_txt2mat(txt_filename)
% fictrac_txt2mat: reads out txt files generated by fictrac and adds a
%   variable to vDat mat file.
%
% Usage:
%   fictrac_txt2mat(txt_filename)
%
% Args:
%   txt_filename: name of txt file to load
% 
% Notes
%   it generates the structure 'fictDat' and saves it to '_vDat.mat'
%   this setup x = yaw, y = pitch, z = roll (this needs to be tested for every setup)
%   this setup y = forward and x = lateral

fictDat = struct('varNames', [], 'var',  []);

% Variable names
fictDat.varNames = {'frame_cnt', ...
    'del_rot_cam_x', 'del_rot_cam_y', 'del_rot_cam_z', ...
    'del_rot_error', ...
    'del_rot_lab_x', 'del_rot_lab_y', 'del_rot_lab_z', ...
    'abs_ori_cam_x', 'abs_ori_cam_y', 'abs_ori_cam_z', ...
    'abs_ori_lab_x', 'abs_ori_lab_x', 'abs_ori_lab_z', ...
    'pos_x', 'pos_y', ...
    'heading', 'direction', 'speed', ...
    'int_x', 'int_y', ...
    'timestamp', 'seq_num'}';

% frame_cnt(1): frame count
% del_rot_cam(2:4): change in orientation since last frame, represented as rotation angle/axis
%   (radians) in camera coordinates, so for this setup x = yaw, y = pitch, z = roll.
% del_rot_error(5): Error score associated with rotation estimate
% del_rot_lab_*(6:8): Change in orientation since last frame, represented as rotation angle/axis
%   (radians) in laboratory coordinates.
% abs_ori_cam_x(9:11): Absolute orientation of the sphere represented as rotation angle/axis
%   (radians) in camera coordinates.
% abs_ori_lab_x(12:14): Absolute orientation of the sphere represented as rotation angle/axis
%   (radians) in laboratory coordinates.
% pos_*(15:16): Integrated x and y position (radians) in laboratory coordinates. Scale by
%   sphere radius for metric position. Incorporates animal's changes in
%   heading
% heading(17): instantaneous heading direction (radians) lab,
%   This is the absolute direction the animal would be facing if it wasn't tethered
% direction(18): instantaneous running direction (radians) lab
%   This is the direction the animal is moving in the lab frame
%   (add to heading to get instantaneous movement direction in world).
% speed(19): instantaneous running speed (radians/frame).
%   Scale by sphere radius for metric speed
% int_*(20:21): integrated forward and side motion
% timestamp(22): time stamps
% seq_num(23): sequence number

dat = readtable(txt_filename, 'ReadVariableNames', false);
fictDat.var = dat{:, 1:23};
clear dat

% save
if exist(strrep(txt_filename, ...
        '_fictrac.txt', '_vDat.mat'), 'file')
    save(strrep(txt_filename, ...
        '_fictrac.txt', '_vDat.mat'), 'fictDat', '-append')
else
    save(strrep(txt_filename, ...
        '_fictrac.txt', '_vDat.mat'), 'fictDat')
end

end
