function [figH, axH] = plot_NoRMCorr_shitfs(im_dim, figH, axH, input_colors, varargin)
% plot_NoRMCorr_shitfs: plot shitfs generated by NoRMCorr
% shifts are separated by dimention: x, y, z | width, height, depth
%
% Usage:
%   [figH, aH] = plot_NoRMCorr_shitfs(im_dim, varargin)
%
% Args:
%   im_dim: image dimensions
%   figH: figure handle
%   axH: axes handle
%   input_colors: axes handle
%   varargin: n number of shifts cells containing
%       shifts in X, shifts in Y, and shifts in Z
%
% Returns:
%   figH: figure handle
%   axH: axes handle

% Get default params
if ~exist('figH', 'var') || isempty(figH)
    figH = figure('position', [560 120 578 828]);
end

if ~exist('axH', 'var') || isempty(axH)
    if im_dim == 3
        axH(1) = subplot(311);
        axH(2) = subplot(312);
        axH(3) = subplot(313);
    else
        axH(1) = subplot(211);
        axH(2) = subplot(212);  
    end
end

if ~exist('input_colors', 'var') || isempty(input_colors)
    input_colors = [1 0 0; 0 0 0; 0 0 1; 0 0.5 0];
end

for i = 1:numel(varargin)

    % get structure shifts_i and plots them
    shifts_i = varargin{i};
    shifts_r = shifts_editor(shifts_i, 'read');
    
    if ~iscell(shifts_r)
        
        shifts_x = shifts_r(:, 2);
        shifts_y = shifts_r(:, 1);
        shifts_z = [];
        if im_dim == 3
            shifts_z = shifts_r(:, 3);
        end
        intCorvect = input_colors(i, :);
        
    else
        
        shifts_x = shifts_r{2};
        shifts_y = shifts_r{1};
        shifts_z = [];
        if im_dim == 3
            shifts_z = shifts_r{3};
        end
        intCorvect = gradientgen(i, size(shifts_x, 2));
        
    end
    
    % plotting
    if size(shifts_x, 2) == 1
        
        ploteachtrace(im_dim, shifts_x, ...
            shifts_y, shifts_z, intCorvect, axH)
        
    else
        
        for j = 1:size(shifts_x, 2)
            ploteachtrace(im_dim, shifts_x(:, j), ...
                shifts_y(:, j), shifts_z(:, j), ...
                intCorvect(j, :), axH)
        end
        
    end
    
    clear shifts_i shifts_r shifts_x shifts_x shifts_z
    
end

linkaxes(axH, 'x');
figEdit(axH, figH)

end

function ploteachtrace(im_dim, shifts_x, shifts_y, shifts_z, icolor, ax)
% ploteachtrace: plots shifts_x, shifts_y, shifts_z on axes ax
%
% Usage:
%   ploteachtrace(im_dim, shifts_x, shifts_y, shifts_z, icolor, ax)
%
% Args:
%   im_dim: image dimensions
%   shifts_x: shifts in X
%   shifts_y: shifts in Y
%   shifts_z: shifts in Z
%   icolor: input color
%   ax: axes handle

plot(shifts_x, 'color', icolor, 'linewidth', 2, 'Parent', ax(1));
plot(shifts_y, 'color', icolor, 'linewidth', 2, 'Parent', ax(2)); 

hold(ax(1), 'on');
hold(ax(2), 'on')

title(ax(1), 'displacements along x', 'fontsize', 14, 'fontweight', 'bold')
title(ax(2), 'displacements along y', 'fontsize', 14, 'fontweight', 'bold')

xlabel(ax(1), 'timestep', 'fontsize', 14, 'fontweight', 'bold')
xlabel(ax(2), 'timestep', 'fontsize', 14, 'fontweight', 'bold')

if im_dim == 3
    plot(shifts_z, 'color', icolor, 'linewidth', 2, 'Parent', ax(3));
    hold(ax(3), 'on')
    title(ax(3), 'displacements along z', 'fontsize', 14, 'fontweight', 'bold')
    xlabel(ax(3), 'timestep', 'fontsize', 14, 'fontweight', 'bold')           
end

end
